steps:
  - id: dockerise
    name: gcr.io/google.com/cloudsdktool/cloud-sdk:latest
    entrypoint: 'sh'
    args:
      - -c
      - |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/single-odyssey-305316/test-artifact-repository/birthday:$SHORT_SHA -t  us-central1-docker.pkg.dev/single-odyssey-305316/test-artifact-repository/birthday:latest
        docker push --all-tags us-central1-docker.pkg.dev/single-odyssey-305316/test-artifact-repository/birthday